# Generated by Django 5.0.1 on 2024-01-22 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="facebook",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="user",
            name="pagina_web",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
